# base configuration file for Colombia
countries: ["CO"]

enable:
  retrieve_databundle: true
  build_natura_raster: false
  progress_bar: false

run:
  name: "CO_2020" # use this to keep track of runs with different settings
  shared_cutouts: true # set to true to share the default cutout(s) across runs

scenario:
  simpl: [""]
  ll: ["copt"]
  clusters: [10]
  opts: [Co2L-24h]
  planning_horizons: # investment years for myopic and perfect; or costs year for overnight
  - 2020

snapshots:
  start: "2013-01-01"
  end: "2014-01-01"
  inclusive: "left" # end is not inclusive

solving:
  solver:
    name: gurobi
    options: gurobi-default